# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: "0 0 * * 0"

permissions:
  contents: write
  actions: read

jobs:
  Backend:
    name: analyse and build backend
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Build productservice
        run: |
          echo "run unit test and build .net application"
          cd /bookingPlatform/productService/
          dotnet restore ProductService.API/ProductService.API.csproj
          dotnet build ProductService.API/ProductService.API.csproj -c Release
          dotnet test ProductServiceTest/ProjectService.Test.Unit.csproj
          dotnet publish ProductService.API/ProductService.API.csproj -c Release -o publish
